# Generated by Django 3.2.8 on 2021-10-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_ledger_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='balance',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
